@startuml
hide empty description

[*] -up-> jiangsu_university
jiangsu_university -up-> State2
State2 -up-> State3
State3 -up-> State4
State4 -up-> State5
State5 -up-> B*bit
B*bit -up-> [*]

jiangsu_university : this is a string,this is a string,this is a string,this is a string,this is a string
jiangsu_university : this is another string

State2 : this is a string
State2 : this is another string

State3 : this is a string
State3 : this is another string

State4 : this is a string
State4 : this is another string

State5 : this is a string
State5 : this is another string

B*bit : this is a string
B*bit : this is another string


@enduml
