@startuml
hide empty description

[*] -up-> JIANGSU_UNIVERSITY
JIANGSU_UNIVERSITY -up-> TONGJI_UNIVERSITY
TONGJI_UNIVERSITY -up-> SAIC_Volkswagen_company
SAIC_Volkswagen_company -up-> ANJINAVI_company
ANJINAVI_company -up-> Phoenix_Automotive_company
Phoenix_Automotive_company -up-> By_bit_company
By_bit_company -up-> [*]

JIANGSU_UNIVERSITY : this is a string,this is a string,this is a string,this is a string,this is a string
JIANGSU_UNIVERSITY : this is another string

TONGJI_UNIVERSITY : this is a string
TONGJI_UNIVERSITY : this is another string

SAIC_Volkswagen_company : this is a string
SAIC_Volkswagen_company : this is another string

ANJINAVI_company : this is a string
ANJINAVI_company : this is another string

Phoenix_Automotive_company : this is a string
Phoenix_Automotive_company : this is another string

By_bit : this is a string
By_bit : this is another string


@enduml
